version: '3.8'
services:
    api:
        image: api
        container_name: api
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "4080:4080"
            - "5678:5678"
        volumes:
            - ./:/app
